import { config } from "dotenv";
config();

import { PrismaClient, Prisma } from "@prisma/client";
import type { MobilePlanMeta, InternetPlanMeta } from "../src/lib/planMeta";

const prisma = new PrismaClient();

const alternatives = [
  // ── Téléphonie mobile ─────────────────────────────────────────────────────
  {
    category: "téléphonie mobile",
    name: "Prixtel Le Petit",
    price: 99.88,
    currency: "EUR",
    description: "Data variable 50 Mo–200 Mo, appels/SMS/MMS illimités, sans engagement",
    affiliateUrl: null,
    isActive: true,
    planMeta: {
      dataGb: 1,
      unlimitedData: false,
      unlimitedCalls: true,
      unlimitedSms: true,
      options: [],
    } satisfies MobilePlanMeta,
  },
  {
    category: "téléphonie mobile",
    name: "B&You 5G 50 Go",
    price: 119.88,
    currency: "EUR",
    description: "50 Go 5G, appels/SMS/MMS illimités, sans engagement",
    affiliateUrl: null,
    isActive: true,
    planMeta: {
      dataGb: 50,
      unlimitedData: false,
      unlimitedCalls: true,
      unlimitedSms: true,
      options: [],
    } satisfies MobilePlanMeta,
  },
  {
    category: "téléphonie mobile",
    name: "RED by SFR 100 Go",
    price: 120.0,
    currency: "EUR",
    description: "100 Go 4G/5G, appels illimités, sans engagement",
    affiliateUrl: null,
    isActive: true,
    planMeta: {
      dataGb: 100,
      unlimitedData: false,
      unlimitedCalls: true,
      unlimitedSms: true,
      options: [],
    } satisfies MobilePlanMeta,
  },
  {
    category: "téléphonie mobile",
    name: "Bouygues B&You 200 Go",
    price: 179.88,
    currency: "EUR",
    description: "200 Go 5G, appels illimités, 25 Go roaming Europe inclus",
    affiliateUrl: null,
    isActive: true,
    planMeta: {
      dataGb: 200,
      unlimitedData: false,
      unlimitedCalls: true,
      unlimitedSms: true,
      options: ["roaming_europe", "hotspot"],
    } satisfies MobilePlanMeta,
  },
  {
    category: "téléphonie mobile",
    name: "Free Mobile 5G 300 Go",
    price: 239.88,
    currency: "EUR",
    description: "300 Go 5G, appels illimités, roaming 35 pays inclus",
    affiliateUrl: null,
    isActive: true,
    planMeta: {
      dataGb: 300,
      unlimitedData: false,
      unlimitedCalls: true,
      unlimitedSms: true,
      options: ["roaming_europe", "hotspot"],
    } satisfies MobilePlanMeta,
  },

  // ── Internet box ──────────────────────────────────────────────────────────
  {
    category: "internet box",
    name: "RED Box Fibre",
    price: 227.88,
    currency: "EUR",
    description: "Fibre jusqu'à 500 Mb/s, TV incluse, sans engagement",
    affiliateUrl: null,
    isActive: true,
    planMeta: {
      downloadSpeedMbps: 500,
      tvIncluded: true,
      options: [],
    } satisfies InternetPlanMeta,
  },
  {
    category: "internet box",
    name: "Bouygues Bbox Fibre",
    price: 287.88,
    currency: "EUR",
    description: "Fibre jusqu'à 2 Gb/s, TV 4K, Wi-Fi 6",
    affiliateUrl: null,
    isActive: true,
    planMeta: {
      downloadSpeedMbps: 2000,
      tvIncluded: true,
      options: ["wifi6", "tv4k"],
    } satisfies InternetPlanMeta,
  },
  {
    category: "internet box",
    name: "Free Freebox Pop",
    price: 299.88,
    currency: "EUR",
    description: "Fibre jusqu'à 2 Gb/s, Player TV 4K, Wi-Fi 6",
    affiliateUrl: null,
    isActive: true,
    planMeta: {
      downloadSpeedMbps: 2000,
      tvIncluded: true,
      options: ["wifi6", "tv4k"],
    } satisfies InternetPlanMeta,
  },
  {
    category: "internet box",
    name: "SFR Box 8",
    price: 359.88,
    currency: "EUR",
    description: "Fibre jusqu'à 2 Gb/s, Wi-Fi 6E",
    affiliateUrl: null,
    isActive: true,
    planMeta: {
      downloadSpeedMbps: 2000,
      tvIncluded: false,
      options: ["wifi6e"],
    } satisfies InternetPlanMeta,
  },
  {
    category: "internet box",
    name: "Orange Livebox Max",
    price: 419.88,
    currency: "EUR",
    description: "Fibre jusqu'à 8 Gb/s, Wi-Fi 6E, TV 4K multi-room",
    affiliateUrl: null,
    isActive: true,
    planMeta: {
      downloadSpeedMbps: 8000,
      tvIncluded: true,
      options: ["wifi6e", "tv4k"],
    } satisfies InternetPlanMeta,
  },

  // ── Streaming ─────────────────────────────────────────────────────────────
  {
    category: "streaming",
    name: "Crunchyroll",
    price: 59.88,
    currency: "EUR",
    description: "Anime en simulcast, sous-titres et doublages FR, catalogue complet",
    affiliateUrl: null,
    isActive: true,
    planMeta: Prisma.JsonNull,
  },
  {
    category: "streaming",
    name: "Amazon Prime Video",
    price: 69.99,
    currency: "EUR",
    description: "Films, séries, productions originales + livraison Prime incluse",
    affiliateUrl: null,
    isActive: true,
    planMeta: Prisma.JsonNull,
  },
  {
    category: "streaming",
    name: "Apple TV+",
    price: 99.99,
    currency: "EUR",
    description: "Productions originales Apple exclusives, qualité 4K Dolby Vision",
    affiliateUrl: null,
    isActive: true,
    planMeta: Prisma.JsonNull,
  },
  {
    category: "streaming",
    name: "Disney+",
    price: 107.88,
    currency: "EUR",
    description: "Disney, Marvel, Star Wars, Pixar, National Geographic",
    affiliateUrl: null,
    isActive: true,
    planMeta: Prisma.JsonNull,
  },
  {
    category: "streaming",
    name: "Netflix Standard",
    price: 167.88,
    currency: "EUR",
    description: "Films et séries en Full HD, 2 écrans simultanés",
    affiliateUrl: null,
    isActive: true,
    planMeta: Prisma.JsonNull,
  },
  {
    category: "streaming",
    name: "Canal+",
    price: 239.88,
    currency: "EUR",
    description: "Sports, cinéma, séries exclusives, Netflix inclus",
    affiliateUrl: null,
    isActive: true,
    planMeta: Prisma.JsonNull,
  },

  // ── Assurance auto ────────────────────────────────────────────────────────
  {
    category: "assurance auto",
    name: "Direct Assurance",
    price: 480.0,
    currency: "EUR",
    description: "100% en ligne, tarif transparent, résiliation en 2 clics",
    affiliateUrl: null,
    isActive: true,
    planMeta: Prisma.JsonNull,
  },
  {
    category: "assurance auto",
    name: "Leocare",
    price: 520.0,
    currency: "EUR",
    description: "App mobile, déclaration de sinistre en 3 min, 100% digital",
    affiliateUrl: null,
    isActive: true,
    planMeta: Prisma.JsonNull,
  },
  {
    category: "assurance auto",
    name: "Lovys",
    price: 540.0,
    currency: "EUR",
    description: "Sans engagement, gestion 100% depuis l'application",
    affiliateUrl: null,
    isActive: true,
    planMeta: Prisma.JsonNull,
  },
  {
    category: "assurance auto",
    name: "Matmut",
    price: 650.0,
    currency: "EUR",
    description: "Réseau d'agences national, bonus fidélité, garanties solides",
    affiliateUrl: null,
    isActive: true,
    planMeta: Prisma.JsonNull,
  },
  {
    category: "assurance auto",
    name: "MAIF",
    price: 700.0,
    currency: "EUR",
    description: "Assurance militante, garanties étendues, statut sociétaire",
    affiliateUrl: null,
    isActive: true,
    planMeta: Prisma.JsonNull,
  },

  // ── Assurance habitation ──────────────────────────────────────────────────
  {
    category: "assurance habitation",
    name: "Direct Assurance",
    price: 120.0,
    currency: "EUR",
    description: "Tarif en ligne compétitif, signature électronique, sans frais de dossier",
    affiliateUrl: null,
    isActive: true,
    planMeta: Prisma.JsonNull,
  },
  {
    category: "assurance habitation",
    name: "Luko",
    price: 144.0,
    currency: "EUR",
    description: "IA pour prévenir les sinistres, remboursement express 24 h",
    affiliateUrl: null,
    isActive: true,
    planMeta: Prisma.JsonNull,
  },
  {
    category: "assurance habitation",
    name: "Lovys",
    price: 156.0,
    currency: "EUR",
    description: "Sans engagement, gestion intégrale depuis l'application mobile",
    affiliateUrl: null,
    isActive: true,
    planMeta: Prisma.JsonNull,
  },
  {
    category: "assurance habitation",
    name: "Matmut",
    price: 192.0,
    currency: "EUR",
    description: "Garanties solides, réseau d'agences nationales, assistance incluse",
    affiliateUrl: null,
    isActive: true,
    planMeta: Prisma.JsonNull,
  },
  {
    category: "assurance habitation",
    name: "MAIF",
    price: 228.0,
    currency: "EUR",
    description: "Valeur à neuf, assistance 24 h/24, protection juridique incluse",
    affiliateUrl: null,
    isActive: true,
    planMeta: Prisma.JsonNull,
  },

  // ── Mutuelle santé ────────────────────────────────────────────────────────
  {
    category: "mutuelle santé",
    name: "Alan Blue",
    price: 480.0,
    currency: "EUR",
    description: "Mutuelle 100% digitale, e-carte bleue, téléconsultation illimitée",
    affiliateUrl: null,
    isActive: true,
    planMeta: Prisma.JsonNull,
  },
  {
    category: "mutuelle santé",
    name: "Henner",
    price: 504.0,
    currency: "EUR",
    description: "Optique et dentaire renforcés, réseau de soins partenaires",
    affiliateUrl: null,
    isActive: true,
    planMeta: Prisma.JsonNull,
  },
  {
    category: "mutuelle santé",
    name: "MAAF",
    price: 540.0,
    currency: "EUR",
    description: "Remboursement rapide, réseau partenaires étendu, devis en ligne",
    affiliateUrl: null,
    isActive: true,
    planMeta: Prisma.JsonNull,
  },
  {
    category: "mutuelle santé",
    name: "Alan Green",
    price: 600.0,
    currency: "EUR",
    description: "Optique 2×/an, dentaire 200%, médecin disponible sans délai",
    affiliateUrl: null,
    isActive: true,
    planMeta: Prisma.JsonNull,
  },
  {
    category: "mutuelle santé",
    name: "Harmonie Mutuelle",
    price: 660.0,
    currency: "EUR",
    description: "Leader mutuelles santé, vaste réseau de soins, accompagnement personnalisé",
    affiliateUrl: null,
    isActive: true,
    planMeta: Prisma.JsonNull,
  },

  // ── Salle de sport ────────────────────────────────────────────────────────
  {
    category: "salle de sport",
    name: "Keep Cool",
    price: 215.88,
    currency: "EUR",
    description: "Piscine + salle, cours collectifs inclus, accès multi-clubs",
    affiliateUrl: null,
    isActive: true,
    planMeta: Prisma.JsonNull,
  },
  {
    category: "salle de sport",
    name: "Basic-Fit Essentiel",
    price: 239.88,
    currency: "EUR",
    description: "Accès à +900 clubs en Europe, ouvert 24 h/24, 7 j/7",
    affiliateUrl: null,
    isActive: true,
    planMeta: Prisma.JsonNull,
  },
  {
    category: "salle de sport",
    name: "Neoness",
    price: 263.88,
    currency: "EUR",
    description: "Salle + piscine, cours collectifs, accès multi-clubs en France",
    affiliateUrl: null,
    isActive: true,
    planMeta: Prisma.JsonNull,
  },
  {
    category: "salle de sport",
    name: "Fitness Park",
    price: 299.88,
    currency: "EUR",
    description: "Équipements premium, cours en live et replay, coaches certifiés",
    affiliateUrl: null,
    isActive: true,
    planMeta: Prisma.JsonNull,
  },
  {
    category: "salle de sport",
    name: "Gymlib",
    price: 360.0,
    currency: "EUR",
    description: "Accès flexible à un réseau de salles partenaires, sans engagement",
    affiliateUrl: null,
    isActive: true,
    planMeta: Prisma.JsonNull,
  },
];

async function main() {
  console.log("Seeding alternatives…");
  await prisma.alternative.deleteMany();
  const { count } = await prisma.alternative.createMany({ data: alternatives });
  console.log(`✓ ${count} alternatives créées`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
